FROM php:8.4-cli

RUN apt-get update \
 && apt-get install -y git unzip curl libicu-dev libzip-dev zlib1g-dev \
 && docker-php-ext-install intl zip \
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app